### ISSUE TITLE
사진 안넣냐 진짜

### ISSUE THREAD

**Issue by sunrabbit123** [Goolgae/learn-to-md#1]
보는 사람 불편하다

**Comment by Goolgae** [comment]
누가 보는거야 근데?

**Comment by sunrabbit123** [comment]
내가 보겠지 
![image](https://user-images.githubusercontent.com/64676070/98509752-1dcf3880-22a5-11eb-9c3f-a1ab54919494.png)

**Comment by sunrabbit123** [comment]
사진 비어있자너
